[package]
name = "mise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
thiserror = "1.0"
anyhow = "1.0"
axum = { version = "0.7.5" }
serde = { version = "1.0.199", features = ["derive"] }
