http_port = 3000
origin = "http://127.0.0.1:3000"
insecure_cookies = true
search_index_directory = "../e2e/search-index"

[oidc]
issuer_url = "http://127.0.0.1:7835"
client_id = "dev-client"
client_secret = "secure-secret"

[sqlite]
db_path = "../e2e/mise.db"
session_db_path = "../e2e/mise_sessions.db"

[images]
backend = "file"

[images.file]
directory = "../e2e/images"
