name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-amd64:
    name: amd64 image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: "${{ inputs.ref }}"

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          provenance: false
          context: "{{defaultContext}}"
          tags: "ghcr.io/bradenrayhorn/mise:building-block-amd64-${{ github.sha }}"
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-amd64
          cache-to: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-amd64,mode=max

  build-arm64:
    name: arm64 image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: "${{ inputs.ref }}"

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          provenance: false
          context: "{{defaultContext}}"
          tags: "ghcr.io/bradenrayhorn/mise:building-block-arm64-${{ github.sha }}"
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-arm64
          cache-to: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-arm64,mode=max

  retag-next:
    name: Push multiarch image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [build-arm64, build-amd64]
    steps:
      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Retag
        run: |
          IMAGE=ghcr.io/bradenrayhorn/mise

          docker buildx imagetools create \
            --tag $IMAGE:next \
            --tag $IMAGE:next-${{ github.sha }} \
            $IMAGE:building-block-amd64-${{ github.sha }} \
            $IMAGE:building-block-arm64-${{ github.sha }}
