name: Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup
        run: |
          VS="0.16.1"
          NAME="cargo-deny"

          curl -L -o ./archive.tar.gz https://github.com/EmbarkStudios/$NAME/releases/download/$VS/$NAME-$VS-x86_64-unknown-linux-musl.tar.gz
          tar -xzvf ./archive.tar.gz --strip-components=1 -C .

      - name: format
        if: always()
        run: cargo fmt --check
      - name: check
        if: always()
        run: cargo check
      - name: clippy
        if: always()
        run: cargo clippy
      - name: licenses
        if: always()
        run: ./cargo-deny check licenses

  test:
    name: Test Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: setup vips
        run: sudo apt-get update && sudo apt-get install -y libvips-tools && vips --version

      - name: Install fake-oidc
        run: go install github.com/bradenrayhorn/fake-oidc@v0

      - name: test
        run: cargo test

  lint-svelte:
    name: Lint Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./ui
        if: always()

      - name: svelte-check
        run: npm run check -- --fail-on-warnings
        working-directory: ./ui
        if: always()

      - name: build
        run: GENERATE_LICENSES=true npm run build
        working-directory: ./ui
        if: always()

  test-svelte:
    name: Test Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Vitest
        run: npm run test:unit
        working-directory: ./ui
        if: always()

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: setup vips
        run: sudo apt-get update && sudo apt-get install -y libvips-tools && vips --version

      - name: Install fake-oidc
        run: go install github.com/bradenrayhorn/fake-oidc@v0

      - name: Install Svelte dependencies
        working-directory: ./ui
        run: npm install

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run Playwright tests
        working-directory: ./e2e
        run: npm run test

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 2
