name: Pull request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: format
        if: always()
        run: cargo fmt --check
      - name: check
        if: always()
        run: cargo check
      - name: clippy
        if: always()
        run: cargo clippy

  test:
    name: Test Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: setup vips
        run: sudo apt-get install -y libvips-tools && vips --version

      - name: Install fake-oidc
        run: go install github.com/bradenrayhorn/fake-oidc@v0

      - name: test
        run: cargo test

