name: Pull request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup
        run: |
          VS="0.16.1"
          NAME="cargo-deny"

          curl -L -o ./archive.tar.gz https://github.com/EmbarkStudios/$NAME/releases/download/$VS/$NAME-$VS-x86_64-unknown-linux-musl.tar.gz
          tar -xzvf ./archive.tar.gz --strip-components=1 -C .

      - name: format
        if: always()
        run: cargo fmt --check
      - name: check
        if: always()
        run: cargo check
      - name: clippy
        if: always()
        run: cargo clippy
      - name: licenses
        if: always()
        run: ./cargo-deny check licenses

  test:
    name: Test Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: setup vips
        run: sudo apt-get update && sudo apt-get install -y libvips-tools && vips --version

      - name: Install fake-oidc
        run: go install github.com/bradenrayhorn/fake-oidc@v0

      - name: test
        run: cargo test

  lint-svelte:
    name: Lint Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./ui
        if: always()

      - name: svelte-check
        run: npm run check -- --fail-on-warnings
        working-directory: ./ui
        if: always()

      - name: build
        run: GENERATE_LICENSES=true npm run build
        working-directory: ./ui
        if: always()

  test-svelte:
    name: Test Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Vitest
        run: npm run test:unit
        working-directory: ./ui
        if: always()

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: setup vips
        run: sudo apt-get update && sudo apt-get install -y libvips-tools && vips --version

      - name: Install fake-oidc
        run: go install github.com/bradenrayhorn/fake-oidc@v0

      - name: Install Svelte dependencies
        working-directory: ./ui
        run: npm install

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run Playwright tests
        working-directory: ./e2e
        run: npm run test

      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 2
